### PR TITLE
Changes.slaya110

### PR DESCRIPTION
**Pull request by slaya110**
pull'd away

### CODE REVIEW

**Comment by slaya110** [comment]
pullin' away

**Comment by crertel** [comment]
OMG so much work.

**Comment by slaya110** [comment]
I know right?! XDDDDDDDDDD

**Comment by atrimahapatra** [comment]
Learning Pull request

**Comment by callrogernow** [comment]
this is not that bad! it however tests our patience. I would rather go dancing.

**Comment by slaya110** [comment]
patience is a virtue 
-_-

**Pull request merged**
